name: flutter_p3b
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

environment:
  sdk: ">=3.0.0 <4.0.0"